return {
  ["workshop-1405120786"]={
    configuration_options={
      amulet_slot=1,
      backpack_slot=1,
      compass_slot=0,
      enable_ui=1,
      render_strategy="neck",
      slots_num=15 
    },
    enabled=true 
  },
  ["workshop-1951468597"]={
    configuration_options={
      CanSpawnSpore=true,
      HouseHammered=false,
      NewInteriors=true,
      NewWalls=false,
      Tardis=true 
    },
    enabled=true 
  },
  ["workshop-2069206134"]={
    configuration_options={
      BundleItems=true,
      DragonflyChest=true,
      EmptyContainerIgnored=true,
      Icebox=true,
      SaltBox=true 
    },
    enabled=true 
  },
  ["workshop-2097358269"]={
    configuration_options={
      collect_items_dist0=6,
      collect_items_dist1=9,
      dragonflychest=1,
      icebox=1,
      is_collect_drop=1,
      is_collect_lootdropper=1,
      is_collect_open=1,
      is_collect_periodicspawner=1,
      is_collect_take=1,
      iscollectone=1,
      minisign_dist=3,
      saltbox=1,
      treasurechest=1,
      ["收集时机"]=false,
      ["箱子种类"]=false,
      ["距离设置 (4 == 一块地皮)"]=false,
      ["收集种类限制"]=false 
    },
    enabled=true 
  },
  ["workshop-2371484058"]={
    configuration_options={ FoodSp=-10, fsbox=0, mrlt=-1, myth_ft=0, myth_ga=0.1, sis_dt=-1, slbox=-10 },
    enabled=true 
  },
  ["workshop-2675609101"]={
    configuration_options={
      auto=true,
      circle=false,
      damage=80,
      display=1,
      durability=-1,
      fix=1,
      language=true,
      make=true,
      number=3,
      radius=3.75,
      recipe=1,
      repairable=true,
      shining=false,
      slot=0 
    },
    enabled=true 
  },
  ["workshop-2682120876"]={ configuration_options={ BUTTON=114 }, enabled=true },
  ["workshop-2725483348"]={ configuration_options={  }, enabled=true },
  ["workshop-2751353390"]={ configuration_options={  }, enabled=true },
  ["workshop-2753142497"]={
    configuration_options={
      [""]=0,
      Sleep_light_intensity=0.1,
      Sleep_light_range=1,
      a_dummytarget_health=6000,
      a_dummytarget_healthRegen=25,
      a_dummytarget_reflect_damage=30,
      a_dummytarget_reflect_on_off=true,
      abigail_set=true,
      acb_researchlab_refine=true,
      acb_small_icebox_scale=true,
      acb_townportal_Light=true,
      acb_townportal_Tendable=true,
      acb_townportal_Water=true,
      acb_townportal_pickup=true,
      acb_townportal_pickup_YESORNO=true,
      acb_townportal_pickup_YESORNO_interval=0.33,
      backpack_glow_on_off=true,
      big_big_big_box=true,
      big_box_ui_horizontal=0,
      big_box_ui_vertical=80,
      box1=true,
      box2=true,
      box3=true,
      chest_box1=true,
      chest_box2=true,
      chest_box3=true,
      extra_equip_slots_updated=true,
      food_healthup_1_reset=true,
      food_healthup_1_value=5,
      items_go_into_containers_first=true,
      make_a_bundlewrap_chest=true,
      make_chicken_soup=true,
      make_dummytarget=true,
      make_food_healthup_1=true,
      make_food_powerup_1=true,
      make_furnance=true,
      make_garlic_bat=true,
      make_my_storeroom=true,
      make_new_saddle_big_box=true,
      make_new_spicepack=true,
      make_new_wardrobe=true,
      make_pig_pig_bag=true,
      make_pig_pig_pig=true,
      make_reversal_icebox=true,
      my_storeroom_MakeObstaclePhysics=true,
      pack1=true,
      pack2=true,
      pack3=true,
      pack4=true,
      pig_pig_bag_ui=false,
      pig_pig_bag_ui_all=1,
      pig_pig_pig_NEW="chartlet3",
      sack0=true,
      sack1=true,
      sack2=true,
      sack3=true,
      sack4=true,
      set_my_storeroom_getnumslots=80,
      set_preserver=0,
      set_preserver_big_box=0,
      set_preserver_my_storeroom=0,
      set_ui_pack_pack_pack=12,
      set_ui_pack_pack_pack___=12,
      small_box23=true,
      small_box3=true,
      small_icebox_box3=true,
      test_modify_pet=true,
      warly_portableblender=true 
    },
    enabled=true 
  },
  ["workshop-2753774601"]={
    configuration_options={ [""]=0, CD=0, Health_Penalty=0, Language=false, UI="right_above" },
    enabled=true 
  },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=250 }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=0,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=2,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-543945797"]={
    configuration_options={
      amount_of_numbers="default",
      display_mode="waving",
      dmg_only="on",
      number_size="default",
      show_decimal_points="no" 
    },
    enabled=true 
  },
  ["workshop-934638020"]={ configuration_options={  }, enabled=true } 
}